# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:




style:
- //cdn.bootcss.com/normalize/4.1.1/normalize.min.css
- //cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css
- css/style.css

script:
- //cdn.bootcss.com/jquery/2.1.3/jquery.min.js
#- //cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js
- js/script.js

search: demo